cluster: mainnet-beta

program_ids:
  spl_token: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
  metaplex_token_metadata: metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
  raydium_v4_amm: 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8

mints:
  wrapped_sol: So11111111111111111111111111111111111111112

fees:
  slippage_bps_default: 50
  compute_unit_limit: 1000000
  compute_unit_price_micro_lamports: 0
  jito_tip_lamports: 0

security:
  encrypt_wallets: true
  wallet_pass_env: LAUNCHER_WALLET_PASS

execution:
  timeout_sec: 60
  max_retries: 4
  confirm_commitment: finalized
